### ISSUE TITLE
yo angular error

### ISSUE THREAD

**Issue by ghost** [yeoman/generator-webapp_DEPRECATED#542] opened 2015-05-14 11:07 UTC
module.js:338
    throw err;
          ^
Error: Cannot find module 'coffee-script'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/vagrant/MyProjects/yo-in-action/node_modules/grunt/lib/grunt.js:16:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by arthurvr** [comment] 2015-05-14 11:22
> yo angular

Dupe of https://github.com/yeoman/generator-angular/issues/1088 and doesn't really have anything to do with `generator-webapp`.

**Closed as completed by arthurvr** 2015-05-14 11:22 UTC
