### ISSUE TITLE
livereload for js and scss doesn't work !!

### ISSUE THREAD

**Issue by baraamashaal** [yeoman/generator-webapp_DEPRECATED#583] opened 2015-08-09 14:54 UTC
in my main computer where i create the project every thing worked perfectly !!
but when i cloned my project on another computer live reload for js and scss doesn't  work!! no scss injected no live reload for the js  i have to reload it manually !!

i create a new webapp project on my second computer but nothing solved

**Comment by eddiemonge** [comment] 2015-08-09 19:49
Did you run `npm install` and `bower install` on the second computer?

**Comment by mawnoy** [comment] 2015-08-10 11:05
I think it's the same problem with #582

**Comment by baraamashaal** [comment] 2015-08-10 16:06
off course :)
every thing working perfectly except live reload with js and css

**Comment by eddiemonge** [comment] 2015-08-10 17:57
You didnt get any errors or anything in chrome developer tools or in terminal?

**Comment by eddiemonge** [comment] 2015-08-10 17:58
I am going to mark as a duplicate of #579. If a fix found for there doesn't work for you then we can reopen this

**Closed as completed by eddiemonge** 2015-08-10 17:58 UTC
Labels: duplicate
